### ISSUE TITLE
Meet minio file access denied when waiting for the controller

### ISSUE THREAD

**Issue by edwardstudy** [apache/incubator-openwhisk-devtools#139]
Hi, I just ran `make quick-start` and wait a long time for the controller to come up:

```
recreate or update the document on the local_subjects database ----------------------------------------------------------------------------------------------------------------------------------- 1531450948.90s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.44s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.24s
check if local_subjects with CouchDB exists --------------------------------------------------------------------------------------------------------------------------------------------------------- 1.37s
create local_whisks with CouchDB -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.96s
recreate or update the document on the local_activations database ----------------------------------------------------------------------------------------------------------------------------------- 0.87s
delete the local_whisks with CouchDB ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.86s
include_tasks --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.74s
check for _design/subjects document in local_subjects database -------------------------------------------------------------------------------------------------------------------------------------- 0.50s
check if local_activations with CouchDB exists ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.44s
check if local_whisks with CouchDB exists ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.44s
include_tasks --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.41s
include_tasks --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.31s
check for _design/snapshotFilters document in local_activations database ---------------------------------------------------------------------------------------------------------------------------- 0.29s
check for _design/snapshotFilters document in local_whisks database --------------------------------------------------------------------------------------------------------------------------------- 0.29s
delete the local_activations with CouchDB ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.29s
check for _design/whisks.v2.1.0 document in local_whisks database ----------------------------------------------------------------------------------------------------------------------------------- 0.28s
recreate or update the document on the local_activations database ----------------------------------------------------------------------------------------------------------------------------------- 0.28s
check for _design/whisks-filters.v2.1.0 document in local_activations database ---------------------------------------------------------------------------------------------------------------------- 0.28s
recreate or update the document on the local_activations database ----------------------------------------------------------------------------------------------------------------------------------- 0.28s
waiting for the Whisk controller to come up ...
..
```

And docker-compose return error about file access denied:
```
minio_1            | API: HeadObject(bucket=api-gateway, object=.git/objects/ec/bc7db6882198974ad92f75db76280e82504653)
minio_1            | Time: 02:58:16 UTC 07/13/2018
minio_1            | RemoteHost: 172.18.0.9:59790
minio_1            | UserAgent: rclone/v1.42-DEV
minio_1            | Error: file access denied
minio_1            |        1: cmd/fs-v1-helpers.go:222:cmd.fsStatDir()
minio_1            |        2: cmd/fs-v1.go:566:cmd.(*FSObjects).getObjectInfo()
minio_1            |        3: cmd/fs-v1.go:630:cmd.(*FSObjects).getObjectInfoWithLock()
minio_1            |        4: cmd/fs-v1.go:635:cmd.(*FSObjects).GetObjectInfo()
minio_1            |        5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
minio_1            |        6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
minio_1            |        7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
minio_1            |        8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
minio_1            |
minio_1            | API: ListObjectsV1(bucket=api-gateway)
minio_1            | Time: 02:58:16 UTC 07/13/2018
minio_1            | RemoteHost: 172.18.0.9:59808
minio_1            | UserAgent: rclone/v1.42-DEV
minio_1            | Error: file access denied
minio_1            |        1: cmd/fs-v1-helpers.go:222:cmd.fsStatDir()
minio_1            |        2: cmd/fs-v1.go:566:cmd.(*FSObjects).getObjectInfo()
minio_1            |        3: cmd/fs-v1.go:1009:cmd.(*FSObjects).ListObjects.func1()
minio_1            |        4: cmd/fs-v1.go:1046:cmd.(*FSObjects).ListObjects()
```

**Comment by ddragosd** [comment]
@edwardstudy these 2 errors shouldn't be related. Would you be able to share the Invoker [logs](https://github.com/apache/incubator-openwhisk-devtools/tree/master/docker-compose#logs) ?

**Comment by gazben** [comment]
@edwardstudy Is this resolved for you? I have the same error?

@ddragosd My invoker logs contains a lot of these:
```
[2018-07-19T12:27:37.463Z] [ERROR] [#tid_sid_invokerNanny] [RuncClient] code: 1 , stdout: , stderr: open /run/runc/f9b9c3552c93dddc622bacba79e21f6541a19dba6a18d242c242d7af828b247d/state.json: no such file or directory [marker:invoker_runc.pause_error:149558:539]
[2018-07-19T12:27:37.528Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess] running /usr/bin/docker rm -f f9b9c3552c93dddc622bacba79e21f6541a19dba6a18d242c242d7af828b247d (timeout: 1 minute) [marker:invoker_docker.rm_start:149564]

```

**Comment by gazben** [comment]
Another note: During the `make quick-start` command there is this error message:
```
checking required ports ... 
 ... OK
  ... preparing api-gateway configuration
Creating openwhisk_minio_1 ... done
.<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>generating server certificate request

```

**Comment by gazben** [comment]
FYI: the error does not occur on Ubuntu 14.04

**Comment by matthewpflueger** [comment]
I'm not sure a two-month-old minio is actually the cause but upgrading fixes this issue on my Mac.

Darwin Matthews-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:59:54 PDT 2018; root:xnu-4570.71.2~2/RELEASE_X86_64 x86_64

**Comment by edwardstudy** [comment]
@ddragosd Hi, sorry for late. I just wanted to reproduce it but everything worked well after reboot.

**Comment by fmaschler** [comment]
I had the same issue with a waiting controller and of the following log:
```
[2018-07-31T12:54:59.314Z] [INFO] [#tid_sid_unknown] [Config] environment set value for port
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:322)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:50)
        at whisk.connector.kafka.KafkaMessagingProvider$.ensureTopic(KafkaMessagingProvider.scala:56)
        at whisk.core.controller.Controller$$anonfun$main$3.apply(Controller.scala:251)
        at whisk.core.controller.Controller$$anonfun$main$3.apply(Controller.scala:249)
        at scala.collection.immutable.Map$Map4.foreach(Map.scala:188)
        at whisk.core.controller.Controller$.main(Controller.scala:249)
        at whisk.core.controller.Controller.main(Controller.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)
        at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:345)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:315)
        ... 7 more
```

Updading minio as suggested in #140 didn't help but by increasing memory the controller started. Though "Access denied" still shows but seems to be ignored.
```
Creating openwhisk_minio_1 ... done
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>generating server certificate request
```

Now the invoker won't start with the following log message:
```
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
[2018-08-01T10:47:34.406Z] [INFO] Slf4jLogger started
[2018-08-01T10:47:35.428Z] [INFO] [#tid_sid_unknown] [Config] environment set value for whisk.api.host.name
[2018-08-01T10:47:35.432Z] [INFO] [#tid_sid_unknown] [Config] environment set value for zookeeper.hosts
[2018-08-01T10:47:35.434Z] [INFO] [#tid_sid_unknown] [Config] environment set value for runtimes.manifest
[2018-08-01T10:47:35.436Z] [INFO] [#tid_sid_unknown] [Config] environment set value for kafka.hosts
[2018-08-01T10:47:35.437Z] [INFO] [#tid_sid_unknown] [Config] environment set value for port
[2018-08-01T10:47:37.376Z] [ERROR] [#tid_sid_invoker] [Invoker] Error processing command line arguments List(0)
```

Any ideas on that?

@gazben On Ubuntu 14.04. conflicting docker and docker-compose versions caused problems. Instead of fixing those I would rather run the newer system.

@edwardstudy I also tried several restarts without success.

System:
* Ubuntu 18.04.
* Docker 18.03.1-ce
* docker-compose 1.22.0

**Comment by chetanmeh** [comment]
```[2018-08-01T10:47:37.376Z] [ERROR] [#tid_sid_invoker] [Invoker] Error processing command line arguments List(0)```

@fmaschler At least this issue now fixed with #146

**Comment by fmaschler** [comment]
Indeed `make quick-start` runs through now. Though the message "Access Denied" persists. @edwardstudy said it worked for him so maybe this issue is solved as well?

**Comment by ddragosd** [comment]
> the message "Access Denied" persists

This is actually OK, as the script waits for docker container to come up and there's a curl command that waits until the container responds with 200. See https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/Makefile#L181 
It's unfortunately confusing when debugging errors b/c this one pops up. Probably another option would be to `sleep 5` first, and then to the `curl`, hoping that in most of the cases the system is fast enough to start the container within `5s` ...

**Comment by fmaschler** [comment]
I see... Well then this issue seems to be solved. The related #140 is merged anyway.
