### ISSUE TITLE
make quick-start fails / whisk controller not coming up

### ISSUE THREAD

**Issue by dakoller** [apache/incubator-openwhisk-devtools#152]
On my Ubuntu-VM (hosted by Win10-Virtualbox) using "make quick-start" hangs at the start of the whisk-controller.

The controller log says: Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a whisk.core.loadBalancer.ShardingContainerPoolBalancerConfig. Failures are:
  at 'whisk.loadbalancer':
    - Key not found: 'invoker-user-memory'.

	at pureconfig.package$.getResultOrThrow(package.scala:138)
	at pureconfig.package$.loadConfigOrThrow(package.scala:160)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer.<init>(ShardingContainerPoolBalancer.scala:159)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer$.instance(ShardingContainerPoolBalancer.scala:437)
	at whisk.core.controller.Controller.<init>(Controller.scala:117)
	at whisk.core.controller.Controller$.main(Controller.scala:258)
	at whisk.core.controller.Controller.main(Controller.scala)
[2018-08-26T16:45:36.615Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Exiting completed
[2018-08-26T16:45:36.615Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Shutting down...
[INFO] [08/26/2018 16:45:36.642] [kamon-akka.actor.default-dispatcher-10] [akka://kamon/user/metrics] Message [kamon.metric.SubscriptionsDispatcher$Tick$] without sender to Actor[akka://kamon/user/metrics#466360108] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2018-08-26T16:45:36.664Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Successfully shut down
[2018-08-26T16:45:36.675Z] [INFO] [#tid_sid_unknown] [Controller] Shutting down Kamon with coordinated shutdown
[2018-08-26T16:45:36.694Z] [INFO] Shutting down remote daemon.
[2018-08-26T16:45:36.700Z] [INFO] Remote daemon shut down; proceeding with flushing remote transports.
[2018-08-26T16:45:36.826Z] [INFO] Remoting shut down
[2018-08-26T16:45:36.829Z] [INFO] Remoting shut down.
[ERROR] [08/26/2018 16:45:36.884] [controller-actor-system-dispatchers.kafka-dispatcher-20] [Controller$(akka://controller-actor-system)] [#tid_sid_unknown] [KafkaConsumerConnector] poll timeout occurred. Retrying 3 more times.
"

(Setting DOCKER_HOST_IP as in another ticket resulted in an error message, which comes up wayearlier: "Recreating openwhisk_apigateway_1    ... 
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...] [flags]

Recreating openwhisk_apigateway_1    ... done
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...] [flags]

Return low-level information on Docker objects
invalid argument "db:" for "--add-host" flag: invalid IP address in add-host: ""
See 'docker run --help'.
Makefile:235: recipe for target 'init-couchdb' failed
make: *** [init-couchdb] Error 125
")

**Comment by paolasoto88** [comment]
Same here with different working environments. 
1. Mac OS High Sierra
2. Linux 18.04 LTS VM running on Azure infrastructure. 

Logs in tmp/openwhisk/controller/logs/controller-local_logs.log
`Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a whisk.core.loadBalancer.ShardingContainerPoolBalancerConfig. Failures are:
  at 'whisk.loadbalancer':
    - Key not found: 'invoker-user-memory'.

	at pureconfig.package$.getResultOrThrow(package.scala:138)
	at pureconfig.package$.loadConfigOrThrow(package.scala:160)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer.<init>(ShardingContainerPoolBalancer.scala:159)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer$.instance(ShardingContainerPoolBalancer.scala:437)
	at whisk.core.controller.Controller.<init>(Controller.scala:117)
	at whisk.core.controller.Controller$.main(Controller.scala:258)
	at whisk.core.controller.Controller.main(Controller.scala)`

**Comment by dgrove-oss** [comment]
Same problem that #151 is working on fixing.  Need to adapt to an upstream change in the arguments to controller/invoker.

**Comment by ddragosd** [comment]
just merged #151 .

**Comment by ddragosd** [comment]
@dakoller , @paolasoto88 I'll leave this ticket open so you can confirm it's working fine for you as well.

**Comment by paolasoto88** [comment]
Great work guys, now the whisk controller is back again. I just pulled recent changes and it worked in both environments. Thanks!

**Comment by Juice10** [comment]
@dakoller can you try pulling the latests code and seeing if it works for you locally?

**Comment by dakoller** [comment]
...it works now..thx for the help!
