### ISSUE TITLE
make quick-start giving API creation failure error

### ISSUE THREAD

**Issue by agrajm** [apache/incubator-openwhisk-devtools#163]
Hi,

I'm trying to run the 3-liner getting started code:
```
$ git clone https://github.com/apache/incubator-openwhisk-devtools.git
$ cd incubator-openwhisk-devtools/docker-compose
$ make quick-start
```
It is failing with the error 
```
creating an API from the hello function ...
ok: updated action hello
error: Unable to create API: API creation failure: Unable to obtain API(s) from the API Gateway: "connect ECONNREFUSED 127.94.0.2:9000"
invoking:
Error invoking the web action
....... << Insert lots of random logs here >> .... 
make: *** [hello-world] Error 1
```
Here are the complete logs - https://gist.github.com/agrajm/2a60e858a499f010f16c2a5d2d986b88

I'm running this on Mac OS X and Java 8 if that matters. Following docker versions
```
docker-compose git:(master) docker --version
Docker version 18.06.1-ce, build e68fc7a
➜  docker-compose git:(master) docker-compose --version
docker-compose version 1.22.0, build f46880f
```

I just installed Docker For mac from [here](https://docs.docker.com/docker-for-mac/install/) - do I need to set some docker specific environment variables for this to work ? 

Can someone please suggest what I can do to debug this?

Regards,
Agraj

**Comment by agrajm** [comment]
Output of `docker ps` command
https://gist.github.com/agrajm/bb49c6238d03144821e6f4ea73257eeb

**Comment by agrajm** [comment]
Hi @csantanapr thanks for detailed steps. Getting the following logs now 
```
➜  incubator-openwhisk-devtools git:(master) wsk --auth $WSKSYSTEMAUTH --insecure activation logs 2a346c0a22cd441ab46c0a22cd241a92
2018-10-06T10:34:41.254872639Z stdout: replaceNamespaceInUrl: namspace=guest url before - https://127.94.0.2/api/v1/web/guest/default/hello.http
2018-10-06T10:34:41.255034466Z stdout: replaceNamespaceInUrl: replacing namespace 'guest' with 'guest'
2018-10-06T10:34:41.255314942Z stdout: replaceNamespaceInUrl: url after - https://127.94.0.2/api/v1/web/guest/default/hello.http
2018-10-06T10:34:41.255923699Z stdout: GW URL        : undefined
2018-10-06T10:34:41.255950604Z stdout: GW URL V2     : http://127.94.0.2:9000/v2
2018-10-06T10:34:41.255954767Z stdout: GW Auth       : undefined
2018-10-06T10:34:41.255957474Z stdout: __ow_user     : guest
2018-10-06T10:34:41.255959798Z stdout: namespace     : guest
2018-10-06T10:34:41.256035294Z stdout: tenantInstance: undefined / openwhisk
2018-10-06T10:34:41.256042132Z stdout: accesstoken   : DUMMY TOKEN
2018-10-06T10:34:41.256044608Z stdout: spaceguid     : 23bc46b1-71f6-4ed5-8c54-816aa4f8c502
2018-10-06T10:34:41.256046926Z stdout: responsetype  : json
2018-10-06T10:34:41.25604905Z  stdout: API name      : undefined
2018-10-06T10:34:41.256051301Z stdout: basepath      : /hello
2018-10-06T10:34:41.256053411Z stdout: relpath       : /world
2018-10-06T10:34:41.256055554Z stdout: GW method     : GET
2018-10-06T10:34:41.256110996Z stdout: action name: hello
2018-10-06T10:34:41.256116494Z stdout: action namespace: guest
2018-10-06T10:34:41.256118951Z stdout: action backendUrl: https://127.94.0.2/api/v1/web/guest/default/hello.http
2018-10-06T10:34:41.256121147Z stdout: action backendMethod: GET
2018-10-06T10:34:41.256123293Z stdout: action authkey: XXXXXXXXXX
2018-10-06T10:34:41.256178952Z stdout: action secureKey: undefined
2018-10-06T10:34:41.256184868Z stdout: calledAsWebAction: true
2018-10-06T10:34:41.256187337Z stdout: apidoc        :
2018-10-06T10:34:41.256190284Z stdout: {"gatewayMethod":"GET","gatewayPath":"/world","gatewayBasePath":"/hello","id":"API:guest:/hello","action":{"name":"hello","backendMethod":"GET","authkey":"23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP","backendUrl":"https://127.94.0.2/api/v1/web/guest/default/hello.http","namespace":"guest"},"namespace":"guest"}
2018-10-06T10:34:41.256346102Z stdout: getApis: querying APIs based on basepath
2018-10-06T10:34:41.256947264Z stdout: getApis: request: {"followAllRedirects":true,"url":"http://127.94.0.2:9000/v2/23bc46b1-71f6-4ed5-8c54-816aa4f8c502/apis","headers":{"Accept":"application/json","User-Agent":"OpenWhisk-apimgmt/1.0.0 OpenWhisk-CLI/1.0 (2018-09-14T17:43:44.288+0000) darwin amd64","Authorization":"Bearer DUMMY TOKEN"},"json":true,"qs":{"basePath":"/hello"}}
2018-10-06T10:34:41.275861524Z stdout: getApis: response status: undefined
2018-10-06T10:34:41.277711084Z stdout: getApis: body type = undefined
2018-10-06T10:34:41.277760589Z stderr: { Error: connect ECONNREFUSED 127.94.0.2:9000
2018-10-06T10:34:41.277764419Z stderr: at Object.exports._errnoException (util.js:1020:11)
2018-10-06T10:34:41.277766885Z stderr: at exports._exceptionWithHostPort (util.js:1043:20)
2018-10-06T10:34:41.277777487Z stderr: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2018-10-06T10:34:41.277780105Z stderr: code: 'ECONNREFUSED',
2018-10-06T10:34:41.277782282Z stderr: errno: 'ECONNREFUSED',
2018-10-06T10:34:41.277784372Z stderr: syscall: 'connect',
2018-10-06T10:34:41.277786481Z stderr: address: '127.94.0.2',
2018-10-06T10:34:41.27778856Z  stderr: port: 9000 }
2018-10-06T10:34:41.277790744Z stderr: Warning: getApis request failed: "connect ECONNREFUSED 127.94.0.2:9000"
2018-10-06T10:34:41.277793073Z stderr: getApis: Unable to obtain API(s) from the API Gateway
2018-10-06T10:34:41.277965321Z stderr: { Error: connect ECONNREFUSED 127.94.0.2:9000
2018-10-06T10:34:41.277977652Z stderr: at Object.exports._errnoException (util.js:1020:11)
2018-10-06T10:34:41.277980993Z stderr: at exports._exceptionWithHostPort (util.js:1043:20)
2018-10-06T10:34:41.277983547Z stderr: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
2018-10-06T10:34:41.277985995Z stderr: code: 'ECONNREFUSED',
2018-10-06T10:34:41.277988188Z stderr: errno: 'ECONNREFUSED',
2018-10-06T10:34:41.277990396Z stderr: syscall: 'connect',
2018-10-06T10:34:41.277992555Z stderr: address: '127.94.0.2',
2018-10-06T10:34:41.277994736Z stderr: port: 9000 }
2018-10-06T10:34:41.278484709Z stdout: makeJsonString: String is not JSON, so need to convert it: SyntaxError: Unexpected token U in JSON at position 0
2018-10-06T10:34:41.278484859Z stderr: API creation failure: Unable to obtain API(s) from the API Gateway: "connect ECONNREFUSED 127.94.0.2:9000"
2018-10-06T10:34:41.27858922Z  stdout: makeErrorResponseObject: isWebAction: true
2018-10-06T10:34:41.278599167Z stdout: makeJsonString: String is not JSON, so need to convert it: SyntaxError: Unexpected token A in JSON at position 0
```
Yup, it looks like action is getting connection refused from the API gateway. 

Also my `docker0` interface is still bound to '172.17.0.0/16' as yours. Running `docker network inspect bridge' gives
```
[
    {
        "Name": "bridge",
        "Id": "1b4b71874236408dc4b9aa170d035407f072bae34787698b172a5969b07af0b9",
        "Created": "2018-10-06T10:03:08.054387632Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```
but when I do `wsk property get --apihost` I always get 
```
whisk API host		127.94.0.2
```
Unsure why its not connecting through the bridge network interface and maybe thats why this error ?

**Comment by agrajm** [comment]
**Update**: my `ifconfig | grep inet` looks like 
```
        inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	inet 127.94.0.2 netmask 0xff000000
	inet 127.94.0.1 netmask 0xff000000
	inet 172.17.0.1 netmask 0xffffff00
	inet6 fe80::81c:17ad:1de2:dcb0%en0 prefixlen 64 secured scopeid 0xc
	inet 10.71.76.84 netmask 0xfffff800 broadcast 10.71.79.255
	inet6 fe80::b461:6aff:fe87:2eb1%awdl0 prefixlen 64 scopeid 0xe
	inet6 fe80::cd8a:e14b:919c:5c62%utun0 prefixlen 64 scopeid 0x10
	inet6 fe80::aede:48ff:fe00:1122%en6 prefixlen 64 scopeid 0x7
```
after I had to manually activate the `docker0` network interface

The culprit addresses `127.94.0.2` and `127.94.0.1` are getting added due to OpenVPN that I'm using at my company. OpenVPN is adding these entries in `/etc/hosts` which is probably causing this issue for me. Any way to tell openwhisk to use the 3rd IP address instead from the above list, if I can't disable OpenVPN ?

**Comment by agrajm** [comment]
Uninstalled OpenVPN - rebooted system - everything works fine. Yay ! 
Not sure how to still use this when I have other entries in my `lo0` interface - thanks to OpenVPN !

**Comment by nikolavukovic** [comment]
Hi, I am having the same problem

error: Unable to create API: API creation failure: Unable to obtain API(s) from the API Gateway: "connect ECONNREFUSED 127.0.0.1:9000"

I am using Ubuntu 16.04 inside virtual machine

docker ps writeout

```CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                    PORTS                                                                                                NAMES
16f0c9dff853        openwhisk/nodejs6action:nightly            "/bin/sh -c 'node --…"   14 minutes ago      Up 14 minutes                                                                                                                  wsk0_2_prewarm_nodejs6
cc55d7d9c21c        openwhisk/nodejs6action:nightly            "/bin/sh -c 'node --…"   14 minutes ago      Up 14 minutes                                                                                                                  wsk0_1_prewarm_nodejs6
4baba1eba26f        landoop/kafka-topics-ui:0.9.3              "/run.sh"                15 minutes ago      Up 15 minutes             0.0.0.0:8001->8000/tcp                                                                               openwhisk_kafka-topics-ui_1
5e7f3e58e727        openwhisk/apigateway:nightly               "/usr/bin/dumb-init …"   15 minutes ago      Up 15 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:9000->9000/tcp, 8423/tcp, 0.0.0.0:9090->8080/tcp   openwhisk_apigateway_1
b08d0fad0af3        openwhisk/invoker:nightly                  "/bin/sh -c 'exec /i…"   15 minutes ago      Up 15 minutes             8080/tcp, 0.0.0.0:8085->8085/tcp, 0.0.0.0:9333->9222/tcp                                             openwhisk_invoker_1
b59a0343ef00        openwhisk/controller:nightly               "/bin/sh -c 'exec /i…"   15 minutes ago      Up 15 minutes             0.0.0.0:2551->2551/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:9222->9222/tcp, 8080/tcp                     openwhisk_controller_1
89354ad7d77d        confluentinc/cp-kafka-rest:3.3.1           "/etc/confluent/dock…"   15 minutes ago      Up 15 minutes             8082/tcp                                                                                             openwhisk_kafka-rest_1
1f7793988f04        wurstmeister/kafka:0.11.0.1                "start-kafka.sh"         15 minutes ago      Up 15 minutes             0.0.0.0:9092->9092/tcp                                                                               openwhisk_kafka_1
b0b472e1fc2f        zookeeper:3.4                              "/docker-entrypoint.…"   15 minutes ago      Up 15 minutes             0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp                               openwhisk_zookeeper_1
5b1a1b28e3d1        redis:2.8                                  "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes             0.0.0.0:6379->6379/tcp                                                                               openwhisk_redis_1
9684f95c1d4f        apache/couchdb:2.3                         "tini -- /docker-ent…"   15 minutes ago      Up 15 minutes             4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp                                                           openwhisk_db_1
918c4d45a3a6        minio/minio:RELEASE.2018-07-13T00-09-07Z   "/usr/bin/docker-ent…"   15 minutes ago      Up 15 minutes (healthy)   0.0.0.0:9001->9000/tcp ```
