### ISSUE TITLE
Problem starting controller

### ISSUE THREAD

**Issue by juandavidgc** [apache/incubator-openwhisk-devtools#174]
Hi! I've followed the steps to install openwhisk using docker-compose. But, when it's installing, I got stucked with this message:
```
waiting for the Whisk controller to come up ...
....................................................................
```
Checking the logs inside the docker of the controller, I got this:

```
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
[2018-11-02T14:59:52.605Z] [INFO] Initializing Kamon...
[INFO] [11/02/2018 14:59:57.375] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[2018-11-02T14:59:57.948Z] [INFO] Slf4jLogger started
[2018-11-02T14:59:58.856Z] [INFO] Starting remoting
[2018-11-02T15:00:00.323Z] [INFO] Remoting started; listening on addresses :[akka.tcp://controller-actor-system@controller:2551]
[2018-11-02T15:00:00.354Z] [INFO] Remoting now listens on addresses: [akka.tcp://controller-actor-system@controller:2551]
[2018-11-02T15:00:00.500Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Starting up...
[2018-11-02T15:00:00.935Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Registered cluster JMX MBean [akka:type=Cluster]
[2018-11-02T15:00:00.946Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Started up successfully
[2018-11-02T15:00:01.250Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - No seed-nodes configured, manual cluster join required
[2018-11-02T15:00:03.694Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.triggers.fires.perMinute
[2018-11-02T15:00:05.587Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.sequence.maxLength
[2018-11-02T15:00:05.588Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.concurrent
[2018-11-02T15:00:05.588Z] [INFO] [#tid_sid_unknown] [Config] environment set value for controller.instances
[2018-11-02T15:00:05.588Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.perMinute
[2018-11-02T15:00:05.594Z] [INFO] [#tid_sid_unknown] [Config] environment set value for runtimes.manifest
[2018-11-02T15:00:05.594Z] [INFO] [#tid_sid_unknown] [Config] environment set value for kafka.hosts
[2018-11-02T15:00:05.594Z] [INFO] [#tid_sid_unknown] [Config] environment set value for port
[2018-11-02T15:02:06.398Z] [WARN] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 could not be created because of org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., retries left: 5
[2018-11-02T15:04:07.400Z] [WARN] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 could not be created because of org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., retries left: 4
[2018-11-02T15:06:08.403Z] [WARN] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 could not be created because of org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., retries left: 3
[2018-11-02T15:08:09.405Z] [WARN] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 could not be created because of org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., retries left: 2
[2018-11-02T15:10:10.405Z] [WARN] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 could not be created because of org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment., retries left: 1
[2018-11-02T15:12:11.413Z] [ERROR] [#tid_sid_unknown] [KafkaMessagingProvider] ensureTopic for completed0 failed due to java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
[2018-11-02T15:12:11.423Z] [ERROR] [#tid_sid_unknown] [Controller] failure during msgProvider.ensureTopic for topic completed0
[2018-11-02T15:12:11.441Z] [INFO] Shutting down remote daemon.
[2018-11-02T15:12:11.442Z] [INFO] Remote daemon shut down; proceeding with flushing remote transports.
[2018-11-02T15:12:11.499Z] [INFO] Remoting shut down
[2018-11-02T15:12:11.501Z] [INFO] Remoting shut down.
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
[2018-11-02T15:33:38.810Z] [INFO] Initializing Kamon...
[INFO] [11/02/2018 15:33:39.873] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[2018-11-02T15:33:40.058Z] [INFO] Slf4jLogger started
[2018-11-02T15:33:40.123Z] [INFO] Starting remoting
[2018-11-02T15:33:40.381Z] [INFO] Remoting started; listening on addresses :[akka.tcp://controller-actor-system@controller:2551]
[2018-11-02T15:33:40.403Z] [INFO] Remoting now listens on addresses: [akka.tcp://controller-actor-system@controller:2551]
[2018-11-02T15:33:40.421Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Starting up...
[2018-11-02T15:33:40.491Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Registered cluster JMX MBean [akka:type=Cluster]
[2018-11-02T15:33:40.493Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - Started up successfully
[2018-11-02T15:33:40.557Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@controller:2551] - No seed-nodes configured, manual cluster join required
[2018-11-02T15:33:41.008Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.triggers.fires.perMinute
[2018-11-02T15:33:41.009Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.sequence.maxLength
[2018-11-02T15:33:41.010Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.concurrent
[2018-11-02T15:33:41.010Z] [INFO] [#tid_sid_unknown] [Config] environment set value for controller.instances
[2018-11-02T15:33:41.011Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.perMinute
[2018-11-02T15:33:41.012Z] [INFO] [#tid_sid_unknown] [Config] environment set value for runtimes.manifest
[2018-11-02T15:33:41.013Z] [INFO] [#tid_sid_unknown] [Config] environment set value for kafka.hosts
[2018-11-02T15:33:41.013Z] [INFO] [#tid_sid_unknown] [Config] environment set value for port
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:370)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:52)
        at whisk.connector.kafka.KafkaMessagingProvider$.ensureTopic(KafkaMessagingProvider.scala:63)
        at whisk.core.controller.Controller$$anonfun$main$3.apply(Controller.scala:247)
        at whisk.core.controller.Controller$$anonfun$main$3.apply(Controller.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at whisk.core.controller.Controller$.main(Controller.scala:245)
        at whisk.core.controller.Controller.main(Controller.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)
        at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:409)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:363)
        ... 7 more
```

Do you know what could be the problem? Thanks in advance,

**Comment by olesiapoz** [comment]
I had the same issue. I have downloaded latest version of incubator-openwhisk-devtools git clone https://github.com/apache/incubator-openwhisk-devtools.git , now it works.

**Comment by juandavidgc** [comment]
That's right, I've updated my local repo and it worked fine. Thanks a lot.
