### ISSUE TITLE
[docker-compose] controller and invoker containers not started due to bad config variables

### ISSUE THREAD

**Issue by duynguyen** [apache/incubator-openwhisk-devtools#29]
As @cagataygurturk and @ddragosd reported in #4, Controller and Invoker containers can not start properly and do not print which environment variables are missing. It only prints `[Controller] Bad configuration, cannot start.`.

My assumption is that there might be changes in some of the existing configurations that make container start-up fail.

**Comment by duynguyen** [comment]
Checked the condition [0] where `Bad configuration, cannot start.` was printed:
```java
if (config.isValid && ExecManifest.initialize(config))
```
I was wondering if this relates to the changed runtimes.manifest structure that could make the config validation fail with the old manifest value ([openwhisk/openwhisk#1980](https://github.com/openwhisk/openwhisk/pull/1980)).

Though not yet successful with the new manifest value.

[0] https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/Controller.scala#L184

**Comment by sandeep-paliwal** [comment]
I am also getting similar issue. Here is exception trace 

2017-05-17T13:14:08.750Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent 
[2017-05-17T13:14:08.751Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute 
[2017-05-17T13:14:08.752Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem 
[2017-05-17T13:14:08.753Z] [INFO] [??] [WhiskConfig] reading properties from consul at consul.docker:8500 
java.util.NoSuchElementException
[2017-05-17T13:14:10.339Z] [WARN] [??] [WhiskConfig] failed to read properties from consul: null 
	at whisk.common.ConsulKeyValueApi$$anonfun$getRecurse$1.apply(ConsulClient.scala:130)
	at whisk.common.ConsulKeyValueApi$$anonfun$getRecurse$1.apply(ConsulClient.scala:126)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2017-05-17T13:14:10.382Z] [ERROR] [??] [Controller] Bad configuration, cannot start.

**Comment by ddragosd** [comment]
This is currently blocked by https://github.com/apache/incubator-openwhisk-devtools/issues/29

**Comment by ddragosd** [comment]
This is currently blocked by https://github.com/apache/incubator-openwhisk/issues/2220

**Comment by ddragosd** [comment]
@duynguyen, @sandeep-paliwal see #32 that should fix the issue here.
