### ISSUE TITLE
Unable to start controller

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk-devtools#93]
Logs from Controller

`ake: *** [init-whisk-cli] Error 1
rtripath-macOS:docker-compose rtripath$ tail -f ~/tmp/openwhisk/controller/logs/controller-local_logs.log 
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2018-02-02T10:30:35.593Z] [INFO] [#tid_6] PUT /api/v1/namespaces/guest/actions/hello overwrite=false
[2018-02-02T10:30:35.594Z] [INFO] [#tid_6] [RestAPIVersion] authenticate: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502
[2018-02-02T10:30:35.597Z] [INFO] [#tid_6] [Identity] [GET] serving from datastore: CacheKey(23bc46b1-71f6-4ed5-8c54-816aa4f8c502) [marker:database_cacheMiss_count:3]
[2018-02-02T10:30:35.601Z] [INFO] [#tid_6] [CouchDbRestStore] [QUERY] 'local_subjects' searching 'subjects/identities [marker:database_queryView_start:3]
[2018-02-02T10:30:35.638Z] [ERROR] [#tid_6] [CouchDbRestStore] Unexpected http response code: 404 Not Found [marker:database_queryView_error:45:42]
[2018-02-02T10:30:35.639Z] [ERROR] [#tid_6] [CouchDbRestStore] [QUERY] 'local_subjects' internal error, failure: 'Unexpected http response code: 404 Not Found' [marker:database_queryView_error:45:42]
[2018-02-02T10:30:35.640Z] [INFO] [#tid_6] [Identity] invalidating CacheKey(23bc46b1-71f6-4ed5-8c54-816aa4f8c502)
[2018-02-02T10:30:35.641Z] [ERROR] [#tid_6] [RestAPIVersion] authentication error: java.lang.Exception: Unexpected http response code: 404 Not Found
[2018-02-02T10:30:35.647Z] [ERROR] Error during processing of request: 'Unexpected http response code: 404 Not Found'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.Exception: Unexpected http response code: 404 Not Found
	at whisk.core.database.CouchDbRestStore$$anonfun$14.apply(CouchDbRestStore.scala:323)
	at whisk.core.database.CouchDbRestStore$$anonfun$14.apply(CouchDbRestStore.scala:295)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

`

Steps to reproduce:
1)Download latest devtools
2)Make quick-start
3)Use any of the wsk actions

**Comment by jthomas** [comment]
Can you paste the full log file from `controller/logs/controller-local_logs.log`?

**Comment by rahulqelfo** [comment]
Here is the  log from the terminal when I do a make quick-start-->

`PLAY RECAP *****************************************************************************************************************************************************
ansible                    : ok=68   changed=0    unreachable=0    failed=0   

Monday 05 February 2018  04:53:42 +0000 (0:00:00.190)       0:00:12.383 ******* 
=============================================================================== 
recreate or update the document on the local_subjects database ------- 1517806414.93s
Gathering Facts --------------------------------------------------------- 1.84s
Gathering Facts --------------------------------------------------------- 1.69s
check if local_subjects with CouchDB exists ----------------------------- 0.28s
include ----------------------------------------------------------------- 0.24s
check for _design/whisks.v2.1.0 document in local_whisks database ------- 0.21s
check if local_whisks with CouchDB exists ------------------------------- 0.21s
check if local_activations with CouchDB exists -------------------------- 0.20s
recreate or update the document on the local_activations database ------- 0.20s
check for _design/snapshotFilters document in local_whisks database ----- 0.20s
check for _design/all-whisks.v2.1.0 document in local_whisks database --- 0.20s
create local_whisks with CouchDB ---------------------------------------- 0.20s
recreate or update the document on the local_whisks database ------------ 0.20s
recreate or update the document on the local_whisks database ------------ 0.20s
check for guest document in local_subjects database --------------------- 0.20s
recreate or update the document on the local_whisks database ------------ 0.20s
recreate or update the document on the local_activations database ------- 0.19s
check for _design/whisks-filters.v2.1.0 document in local_activations database --- 0.19s
check for _design/whisks.v2.1.0 document in local_activations database --- 0.19s
recreate or update the document on the local_activations database ------- 0.19s
waiting for the Whisk controller to come up ... 
.............................`

The above gets stuck forever.


The complete logs from the controller-->

`rtripath-macOS:logs rtripath$ cat controller-local_logs.log 
[2018-02-05T04:53:19.737Z] [INFO] Initializing Kamon...
[INFO] [02/05/2018 04:53:20.578] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[2018-02-05T04:53:20.739Z] [INFO] Slf4jLogger started
[2018-02-05T04:53:22.002Z] [INFO] [??] [Config] environment set value for db.whisk.actions
[2018-02-05T04:53:22.005Z] [INFO] [??] [Config] environment set value for limits.actions.sequence.maxLength
[2018-02-05T04:53:22.006Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2018-02-05T04:53:22.007Z] [INFO] [??] [Config] environment set value for db.protocol
[2018-02-05T04:53:22.008Z] [INFO] [??] [Config] environment set value for akka.cluster.seed.nodes
[2018-02-05T04:53:22.009Z] [INFO] [??] [Config] environment set value for controller.instances
[2018-02-05T04:53:22.010Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2018-02-05T04:53:22.011Z] [INFO] [??] [Config] environment set value for whisk.version.date
[2018-02-05T04:53:22.012Z] [INFO] [??] [Config] environment set value for controller.localBookkeeping
[2018-02-05T04:53:22.013Z] [INFO] [??] [Config] environment set value for db.port
[2018-02-05T04:53:22.013Z] [INFO] [??] [Config] environment set value for whisk.version.buildno
[2018-02-05T04:53:22.014Z] [INFO] [??] [Config] environment set value for db.username
[2018-02-05T04:53:22.016Z] [INFO] [??] [Config] environment set value for db.whisk.activations
[2018-02-05T04:53:22.016Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2018-02-05T04:53:22.027Z] [INFO] [??] [Config] environment set value for db.whisk.auths
[2018-02-05T04:53:22.034Z] [INFO] [??] [Config] environment set value for runtimes.manifest
[2018-02-05T04:53:22.038Z] [INFO] [??] [Config] environment set value for kafka.hosts
[2018-02-05T04:53:22.039Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2018-02-05T04:53:22.041Z] [INFO] [??] [Config] environment set value for controller.ha
[2018-02-05T04:53:22.046Z] [INFO] [??] [Config] environment set value for db.host
[2018-02-05T04:53:22.047Z] [INFO] [??] [Config] environment set value for port
[2018-02-05T04:53:22.052Z] [INFO] [??] [Config] environment set value for db.provider
[2018-02-05T04:53:22.056Z] [INFO] [??] [Config] environment set value for db.password
[2018-02-05T04:53:22.111Z] [ERROR] [??] [Config] required property db.whisk.actions.ddoc still not set
[2018-02-05T04:53:22.112Z] [ERROR] [??] [Controller] Bad configuration, cannot start.
[INFO] [02/05/2018 04:53:22.183] [kamon-shutdown-hook-1] [CoordinatedShutdown(akka://kamon)] Starting coordinated shutdown from JVM shutdown hook
`

**Comment by rabbah** [comment]
required property db.whisk.actions.ddoc still not set. Sounds like a configuration issue which isn’t picking up this property.

**Comment by rahulqelfo** [comment]
@rabbah Any tips on how to make it work?

**Comment by jthomas** [comment]
Random guess - are the docker images for the controller and invoker current? I had an issue before where docker compose won't re-pull the latest images. This means you can be using old images with the current config, which breaks. `docker pull` to update and try again.

**Comment by ddragosd** [comment]
@rahulqelfo I'm closing this issue assuming the solution recommended by @jthomas worked, but feel free to reopen it if you still have issues.
